routes/web.php
// POST /clients, mapped to the store() method,
// GET /clients/{id}, mapped to the show() method,
// GET /clients/{id}/edit, mapped to the edit() method,
// PUT/PATCH /clients/{id}, mapped to the update() method,
// DELETE /clients/{id}, mapped to the destroy() method.
*/
// ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
// Routes for "SUPERADMIN" user Role
// ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
    Route::group(['middleware' => 'auth'], function () {
        Route::get('dashboard', function () { 
            $userRole = Auth::user()->getRole();
            if($userRole == 'superadmin'){
                return redirect('home');
            } else if($userRole == 'admin') {
                return redirect('admin/home');
            } else if($userRole == 'doctor') {
                return redirect('doctor/home');
            } else {
                return redirect('/home');
            }
        });
        // ROUTES for SUPERADMIN
        Route::group(['middleware' => 'role:superadmin'], function () {
            // DASHBOARD
                Route::get('/home', 'HomeController@index')->name('home');
            // Languages
                Route::group(['prefix'=>'configs'], function () {
                    Route::resource('langs', 'LangController');
                });
            // Files
                Route::group(['prefix'=>'configs'], function () {
                    Route::resource('files', 'FileController')->only(['index','edit','update']);
                });
            // Doctor's Services Type
                Route::get('/users/stypes', 'StypeController@index')->name('stypes.index');
                Route::get('/users/stypes/create', 'StypeController@create')->name('stypes.create');
                Route::post('/users/stypes', 'StypeController@store')->name('stypes.store');
                Route::get('/users/stypes/{id}', 'StypeController@show')->name('stypes.show');
                Route::get('/users/stypes/{id}/edit', 'StypeController@edit')->name('stypes.edit');
                Route::put('/users/stypes/{id}', 'StypeController@update')->name('stypes.update');
                Route::patch('/users/stypes/{id}', 'StypeController@update')->name('stypes.update');
                Route::delete('/users/stypes/{id}', 'StypeController@destroy')->name('stypes.destroy');
            // USERS
                Route::get('/users/roles', 'UserController@userRoles')->name('List of Roles');
                Route::post('/users/{id}/trash', 'UserController@trash');
                Route::post('/users/{id}/restore', 'UserController@restore');
                Route::get('/users/createdoc', 'UserController@createdoc')->name('users.createdoc');
                Route::post('/usersdoc', 'UserController@storedoc')->name('users.storedoc');
                Route::get('/usersdoc/{id}/edit', 'UserController@editdoc')->name('users.editdoc');
                Route::put('/usersdoc/{id}', 'UserController@updatedoc')->name('users.updatedoc');
                Route::patch('/usersdoc/{id}', 'UserController@updatedoc')->name('users.updatedoc');
                Route::get('/usersdoc', 'UserController@indexdoc')->name('users.indexdoc');
                Route::resource('users', 'UserController');
            // CLIENTS
                Route::resource('clients', 'ClientController');
            // CATEGORIES
                Route::resource('tags', 'TagController');
            
            // CONTENTS 
                // IDE - GDE
                Route::get('/contents/ide', 'ContentController@ide');
                Route::post('/contents/ide', 'ContentController@ide_store');
                Route::get('/contents/gde', 'ContentController@gde');
                Route::post('/contents/gde', 'ContentController@gde_store');
                // Author
                Route::get('/contents/authors', 'AuthorController@index')->name('authors.index');
                Route::get('/contents/authors/create', 'AuthorController@create')->name('authors.create');
                Route::post('/contents/authors', 'AuthorController@store')->name('authors.store');
                Route::get('/contents/authors/{id}', 'AuthorController@show')->name('authors.show');
                Route::get('/contents/authors/{id}/edit', 'AuthorController@edit')->name('authors.edit');
                Route::put('/contents/authors/{id}', 'AuthorController@update')->name('authors.update');
                Route::patch('/contents/authors/{id}', 'AuthorController@update')->name('authors.update');
                Route::delete('/contents/authors/{id}', 'AuthorController@destroy')->name('authors.destroy');
                // Product
                Route::get('/contents/products', 'ProductController@index')->name('products.index');
                Route::get('/contents/products/create', 'ProductController@create')->name('products.create');
                Route::post('/contents/products', 'ProductController@store')->name('products.store');
                Route::get('/contents/products/{id}', 'ProductController@show')->name('products.show');
                Route::get('/contents/products/{id}/edit', 'ProductController@edit')->name('products.edit');
                Route::put('/contents/products/{id}', 'ProductController@update')->name('products.update');
                Route::patch('/contents/products/{id}', 'ProductController@update')->name('products.update');
                Route::delete('/contents/products/{id}', 'ProductController@destroy')->name('products.destroy');
                Route::resource('contents', 'ContentController');
            // CPAGES
                // Sections
                Route::get('/cpages/csections', 'CsectionController@index')->name('csections.index');
                Route::get('/cpages/csections/create', 'CsectionController@create')->name('csections.create');
                Route::post('/cpages/csections', 'CsectionController@store')->name('csections.store');
                Route::get('/cpages/csections/{id}', 'CsectionController@show')->name('csections.show');
                Route::get('/cpages/csections/{id}/edit', 'CsectionController@edit')->name('csections.edit');
                Route::put('/cpages/csections/{id}', 'CsectionController@update')->name('csections.update');
                Route::patch('/cpages/csections/{id}', 'CsectionController@update')->name('csections.update');
                Route::delete('/cpages/csections/{id}', 'CsectionController@destroy')->name('csections.destroy');
                Route::resource('cpages', 'CpageController');
            // BLOCKS              
                // blocks - advertisement
                Route::get('/blocks/create_advertisement', 'BlockController@create_advertisement');
                Route::post('/blocks/create_advertisement', 'BlockController@store_advertisement');
                Route::patch('/blocks/{id}/edit_advertisement', 'BlockController@update_advertisement');

                // blocks - videos
                Route::get('/blocks/create_video', 'BlockController@create_video');
                Route::post('/blocks/create_video', 'BlockController@store_video');
                Route::patch('/blocks/{id}/edit_video', 'BlockController@update_video');

                // blocks - text
                Route::get('/blocks/create_text', 'BlockController@create_text');
                Route::post('/blocks/create_text', 'BlockController@store_text');
                Route::patch('/blocks/{id}/edit_text', 'BlockController@update_text');

                // blocks - qrcode
                Route::get('/blocks/create_qrcode', 'BlockController@create_qrcode');
                Route::post('/blocks/create_qrcode', 'BlockController@store_qrcode');
                Route::patch('/blocks/{id}/edit_qrcode', 'BlockController@update_qrcode');

                // GLOBAL
                Route::get('/blocks', 'BlockController@index')->name('List of Blocks');
                Route::get('/blocks/{id}', 'BlockController@show');
                Route::get('/blocks/{id}/edit', 'BlockController@edit');
                Route::delete('/blocks/{id}', 'BlockController@destroy');

            // DOCTORS
                Route::post('/doctors/{id}/trash', 'DoctorController@trash');
                Route::resource('doctors', 'DoctorController')->except(['create','store']);               
            
        });
        // ROUTES for ADMIN
        Route::group(['prefix'=>'admin','middleware' => 'role:admin'], function () {
            // DASHBOARD
                Route::get('/home', 'HomeController@index')->name('home');
            // CLIENT
                Route::get('/clients/{id}', 'ClientController@admin_client_detail');
            // CATEGORIES
                Route::resource('tags', 'TagController');  
            // CONTENTS
                Route::resource('contents', 'ContentController');  
            // DOCTORS
                Route::post('/doctors/{id}/trash', 'DoctorController@trash');
                Route::resource('doctors', 'DoctorController')->except(['create','store']);
        });
        // ROUTES for DOCTOR
        Route::group(['prefix'=>'doctor', 'middleware' => 'role:doctor'], function () {
                // DASHBOARD
                Route::get('/home', 'HomeController@index')->name('home');
                // Update Profile
                Route::get('/update-profile', 'UserController@edit_profile')->name('edit_profile');
                Route::post('/update-profile', 'UserController@update_profile')->name('update_profile');
        });
        
        //Route::get('/users/permissions', 'PermissionController@edit')->name('Setup Permissions');
        //Route::post('/users/permissions', 'PermissionController@update');
        //Route::get('/comingsoon', 'comingsoonController@index')->name('ComingSoon Page');
        //Route::get('/permissions', 'PermissionController@Permission');
    });

Auth::routes();
Route::get('/', 'Auth\LoginController@showLoginForm');

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'description',
    ];
    
    public function clients() {
        return $this->belongsToMany(Client::class,'tags_clients');
    }

    public function langs() {
        return $this->belongsToMany(Lang::class,'tags_langs')->withPivot('tag_name', 'tag_description');;
    }

    public function contents() {
        return $this->belongsToMany(Content::class,'contents_tags');
    }
}

resources/views/tags/create.blade.php
@extends('layouts.dashboard')

@section('content')
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<style type="text/css">
    #create_tag_client_listing_form_group{ height: 100px; overflow-y: scroll; }
    #create_tag_client_listing_form_group .form-item{display: flex;}
    #create_tag_client_listing_form_group .form-item input {width: auto; height: auto; margin-right: 5px;}
    #create_tag_client_listing_form_group .form-item label{font-weight: normal;}


    .ui-tabs-vertical { width: 55em; }
    .ui-tabs-vertical .ui-tabs-nav { overflow-y: scroll; max-height: 400px; padding: .2em .1em .2em .2em; float: left; width: 12em; min-height: 400px; overflow-y: scroll;}
    .ui-tabs-vertical .ui-tabs-nav li { clear: left; width: 100%; border-bottom-width: 1px !important; border-right-width: 0 !important; margin: 0 -1px .2em 0; }
    .ui-tabs-vertical .ui-tabs-nav li a { display:block; }
    .ui-tabs-vertical .ui-tabs-nav li.ui-tabs-active { padding-bottom: 0; padding-right: .1em; border-right-width: 1px; }
    .ui-tabs-vertical .ui-tabs-panel { padding: 1em; float: right; width: 40em;}
    body {font-family: Arial, Helvetica, sans-serif;}
    h4.lang-subheading{border-bottom: 2px solid #333;font-weight: bold;background: #F4EAC3;padding: 5px;margin-bottom: 16px;}
    table {font-size: 1em;}
    .ui-draggable, .ui-droppable {background-position: top;}
</style>
<?php 
$role = auth()->user()->getRole();
$role_segment = ($role == 'admin')?'/admin':'';
$base_url  = URL::to('/').$role_segment;
$form_action = $base_url.'/tags';
//{{ route('tags.store') }}
?>
<div class="page-heading"><h3>Add Category</h3></div>
@include('flash-message')
<div class="col-md-8 col-md-offset-2 tags-create-page tags form large-9 medium-8 columns content">
	<section class="panel">
		<div class="panel-body">
            <form method="POST" action="{{ $form_action }}">
            @csrf
                <div class="row">
                    <div class="col-lg-6 col-lg-offset-3">
                        <div id="form-field-clients" class="form-group form-checkbox-wrapper">
                            <label class="required">Clients</label><br />
                            <div id="create_tag_client_listing_form_group" class="form-control">
                                <?php foreach($clients as $k=>$v) { ?>
                                    <div class="form-item">
                                    <input id="client_<?= $v['id'] ?>" type="checkbox" class="form-control @error('client') is-invalid @enderror" name="client[]" value="<?= $v['id'] ?>" autocomplete="client">
                                    <label for="client_<?= $v['id'] ?>"><?= $v['name'] ?></label>
                                    </div>
                                <?php } ?>
                            </div>
                            <span class="help-text">( Choose minimum one client for creating Category. )</span>
                            @error('client')
                                <span class="invalid-feedback msg-error" role="alert"><i class="fa fa-exclamation-triangle"></i> {{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                    
                </div>
                <div class="row">
                    <div class="col-lg-12 ">
                    <div id="tabs">
                        <!-- TABS Labels-->
                        <ul>
                            <?php foreach($langs as $key=>$val) {  ?>
                                <li><a href="#lang-<?= $val['code'] ?>-<?= $val['id'] ?>"><?= $val['name'].' ( '.$val['code'].' )'?></a></li>
                            <?php }  ?>
                        </ul>
                        <!-- TABS Wrappers-->
                        <?php foreach($langs as $key=>$val) {  
                            $reqField = ($val['id'] == '1')?'required':''; // Fields can be required only for english language.
                            ?>
                            <div id="lang-<?= $val['code'] ?>-<?= $val['id'] ?>">
                                <h4 class="lang-subheading" ><?= $val['name'] ?> Language </h4>
                                <div class="row">
                                    <div class="col-lg-8 ">
                                        <div class="form-group">
                                            <label class="<?= $reqField ?>">( <?= $val['code'] ?> ) Category Name</label><br />
                                            <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="langdata[<?= $val['id'] ?>][tag_name]" value="{{ old('name') }}" <?= $reqField ?> >
                                            @error('name')
                                                <span class="invalid-feedback msg-error" role="alert"><i class="fa fa-exclamation-triangle"></i> {{ $message }}</span>
                                            @enderror
                                        </div>
                                        <div class="form-group">
                                            <label>( <?= $val['code'] ?> ) Description</label><br />
                                            <textarea  id="description" name="langdata[<?= $val['id'] ?>][tag_description]" class="form-control @error('description') is-invalid @enderror" cols="5" rows="3">{{ old('description') }}</textarea>
                                            @error('description')
                                                <span class="invalid-feedback msg-error" role="alert"><i class="fa fa-exclamation-triangle"></i> {{ $message }}</span>
                                            @enderror
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php } ?>
                        </div>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-lg-12 text-center">
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">{{ __('Add Category') }}</button>
                        </div>
                    </div>
                </div>
            </form>
		</div>
	</section>
</div>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
@endsection

resources/views/tags/edit.blade.php
@extends('layouts.dashboard')

@section('content')
<?php
$role = auth()->user()->getRole();
$role_segment = ($role == 'admin')?'/admin':'';
$base_url  = URL::to('/').$role_segment;
?>
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<style type="text/css">
    #create_tag_client_listing_form_group{ height: 100px; overflow-y: scroll; }
    #create_tag_client_listing_form_group .form-item{display: flex;}
    #create_tag_client_listing_form_group .form-item input {width: auto; height: auto; margin-right: 5px;}
    #create_tag_client_listing_form_group .form-item label{font-weight: normal;}
    .panel-header{ padding: 10px; }
    .ui-tabs-vertical { width: 55em; }
    .ui-tabs-vertical .ui-tabs-nav { overflow-y: scroll; max-height: 400px; padding: .2em .1em .2em .2em; float: left; width: 12em; min-height: 400px; overflow-y: scroll;}
    .ui-tabs-vertical .ui-tabs-nav li { clear: left; width: 100%; border-bottom-width: 1px !important; border-right-width: 0 !important; margin: 0 -1px .2em 0; }
    .ui-tabs-vertical .ui-tabs-nav li a { display:block; }
    .ui-tabs-vertical .ui-tabs-nav li.ui-tabs-active { padding-bottom: 0; padding-right: .1em; border-right-width: 1px; }
    .ui-tabs-vertical .ui-tabs-panel { padding: 1em; float: right; width: 40em;}
    body {font-family: Arial, Helvetica, sans-serif;}
    h4.lang-subheading{border-bottom: 2px solid #333;font-weight: bold;background: #F4EAC3;padding: 5px;margin-bottom: 16px;}
    table {font-size: 1em;}
    .ui-draggable, .ui-droppable {background-position: top;}
</style>
<?php 
$role = auth()->user()->getRole();
$role_segment = ($role == 'admin')?'/admin':'';
$base_url  = URL::to('/').$role_segment;
$form_action = $base_url.'/tags'.'/'.$tag['id'];
//{{ route('tags.update', $tag['id']) }}
?>
<div class="page-heading"><h3>Update Category</h3></div>
@include('flash-message')
<div class="col-md-8 col-md-offset-2 tags-edit-page tags form large-9 medium-8 columns content">
	<section class="panel">
        <div class="panel-header">
            <div class="row action-items">
                <div class="col-md-6 text-left">
                    <a title="Back to Category Listing" href="<?= $base_url ?>/tags" class="btn btn-primary"><i class="fa fa-backward"></i></a>
                </div>
                <div class="col-md-6 text-right">
                    <a title="View Category" href="<?= $base_url ?>/tags/<?=  $tag['id'] ?>" class="btn btn-primary"><i class="fa fa-search-plus"></i></a>
                </div>
            </div>
        </div>
		<div class="panel-body">
            <form method="post" action="{{ $form_action }}">
            @method('PATCH') 
            @csrf
                <div class="row">
                    <div class="col-lg-6 col-lg-offset-3">
                        <div id="form-field-clients" class="form-group form-checkbox-wrapper">
                            <label class="required">Clients</label><br />
                            <div id="create_tag_client_listing_form_group" class="form-control">
                                <?php foreach($clients as $k=>$v) { ?>
                                    <div class="form-item">
                                    <input  
                                    <?= (in_array($v['id'],$tag['clients']))?'checked':''?> 
                                    
                                    id="client_<?= $v['id'] ?>" type="checkbox" class="form-control @error('client') is-invalid @enderror" name="client[]" value="<?= $v['id'] ?>" autocomplete="client">
                                    <label for="client_<?= $v['id'] ?>"><?= $v['name'] ?></label>
                                    </div>
                                <?php } ?>
                            </div>
                            <span class="help-text">( Choose minimum one client for updating category. )</span>
                            @error('client')
                                <span class="invalid-feedback msg-error" role="alert"><i class="fa fa-exclamation-triangle"></i> {{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12 ">
                    <div id="tabs">
                        <!-- TABS Labels-->
                        <ul>
                            <?php foreach($langs as $key=>$val) {  ?>
                                <li><a href="#lang-<?= $val['code'] ?>-<?= $val['id'] ?>"><?= $val['name'].' ( '.$val['code'].' )'?></a></li>
                            <?php }  ?>
                        </ul>
                        <!-- TABS Wrappers-->
                        <?php foreach($langs as $key=>$val) {  
                            $reqField = ($val['id'] == '1')?'required':''; // Fields can be required only for english language.
                            $tag_name_value = ((!empty($tag['langs'][$val['id']])) && (isset($tag['langs'][$val['id']])))?$tag['langs'][$val['id']]['tag_name']:"";
                            $tag_desc_value = ((!empty($tag['langs'][$val['id']])) && (isset($tag['langs'][$val['id']])))?$tag['langs'][$val['id']]['tag_description']:"";
                            ?>
                            <div id="lang-<?= $val['code'] ?>-<?= $val['id'] ?>">
                                <h4 class="lang-subheading"><?= $val['name'] ?> Language </h4>
                                <div class="row">
                                    <div class="col-lg-8 ">
                                        <div class="form-group">
                                            <label class="<?= $reqField ?>">( <?= $val['code'] ?> ) Category Name</label><br />
                                            <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="langdata[<?= $val['id'] ?>][tag_name]" value="{{ $tag_name_value }}" <?= $reqField ?> >
                                            @error('name')
                                                <span class="invalid-feedback msg-error" role="alert"><i class="fa fa-exclamation-triangle"></i> {{ $message }}</span>
                                            @enderror
                                        </div>
                                        <div class="form-group">
                                            <label>( <?= $val['code'] ?> ) Description</label><br />
                                            <textarea  id="description" name="langdata[<?= $val['id'] ?>][tag_description]" class="form-control @error('description') is-invalid @enderror" cols="5" rows="3">{{ $tag_desc_value }}</textarea>
                                            @error('description')
                                                <span class="invalid-feedback msg-error" role="alert"><i class="fa fa-exclamation-triangle"></i> {{ $message }}</span>
                                            @enderror
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php } ?>
                        </div>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-lg-12 text-center">
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">{{ __('Update Client') }}</button>
                        </div>
                    </div>
                </div>
            </form>
		</div>
	</section>
</div>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
@endsection

resources/views/tags/index.blade.php
@extends('layouts.dashboard')

@section('content')
<div class="page-heading"><h3>List of Categories</h3></div>
@include('flash-message')
<?php 
$role = auth()->user()->getRole();
$role_segment = ($role == 'admin')?'/admin':'';
$base_url  = URL::to('/').$role_segment;
?>
<style type="text/css">
    table tr td.client-doctor-count-col span{display: block; text-align: center;}
</style>
<div class="tags form large-9 medium-8 columns content">
	<section class="panel">
        <div class="panel-heading ">
            <div class="row tags_filters_wrapper bg-secondary">
                <form method="get" id="form_tags_filter" >
                    <div class="col-md-3 form-group">
                        <label>Category Name</label><br />
                        <input class="form-control" type="text" name="tnm" id="tags-filter-tnm" value="<?= (!empty($qry['tnm']))?$qry['tnm']:'' ?>" /> 
                    </div>
                    <div class="col-md-3 form-group">
                        <label>Client</label><br />
                        <select class="form-control @error('cid') is-invalid @enderror" name="cid" id="cid">
                            <option value="">- Select One -</option>
                            @foreach($clients as $k=>$v)
                                <option <?php if((!empty($qry['cid'])) && ($qry['cid'] == $v['id'])){ echo "selected"; } ?> value="{{ $v['id'] }}">{{ $v['name'] }}</option>
                            @endforeach
                        </select>
                    </div>	
                    <div class="col-md-3 form-group">  
                        <label>&nbsp;</label><br />
                        <input type="submit" name="submit" value="Search" class="btn btn-primary" />
                        <a href="<?= $base_url ?>/tags" class="btn btn-secondary">Reset</a>
                    </div>	
                </form>
            </div>	
        </div>
		<div class="panel-body">
        <?php if(count($tags) > 0) { ?>
        <table class="table table-hover general-table">
            <thead>
                <tr>
                    <th width="8%">Cat_Id</th>
                    <th width="12%">Name ( English )</th>
                    <th width="40%">Description ( English )</th>
                    <th width="10%">Clients</th>
                    <th width="20%">Created Date</th>
                    <th width="10%">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach($tags as $tag)
                <tr>
                    <td>{{ $tag['id'] }}</td>
                    <td>{{ $tag['langs']['1']['tag_name'] }}</td>
                    <td>{{ $tag['langs']['1']['tag_description'] }}</td>
                    <td class="tag-doctor-count-col">
                        <span><strong>{{ count($tag['clients']) }}</strong></span>
                        <?php if($role != 'admin') { ?>
                            <span>
                                <a target="_blank" href="<?= $base_url ?>/clients?tid=<?= $tag['id'] ?>" title="View Clients under this Category">[ view ]</a>
                            </span>
                        <?php } ?>
                    </td>
                    <td>{{ date('M d, Y H:i:s',strtotime($tag['created_at'])) }}</td>
                    <td class="actions">
                        <a href="<?= $base_url ?>/tags/<?= $tag['id'] ?>" title="View Category"><i class="fa fa-search-plus"></i></a>&nbsp;&nbsp;
                        <a href="<?= $base_url ?>/tags/<?= $tag['id'] ?>/edit" title="Edit Category"><i class="fa fa-pencil"></i></a>&nbsp;&nbsp;
                    
                        <form name="post_tag_<?= $tag['id'] ?>" style="display:none;" method="post" action="<?= $base_url ?>/tags/<?= $tag['id'] ?>" > @method('DELETE')  @csrf</form>
                        <a href="#" onclick="if (confirm(&quot;Are you sure you want to delete tag <?= $tag['name'] ?>?&quot;)) { document.post_tag_<?= $tag['id'] ?>.submit(); } event.returnValue = false; return false;" title="Delete Category"><i class="fa fa-trash-o"></i></a>
                    </td>
                </tr>
                @endforeach
            <tbody>
        </table>
        <div class="text-center">
            {{ $paginate->links() }}
        </div>
        <?php } else {
            echo '<div class="text-center">No Record Found.</div>';
        } ?>
		</div>
	</section>
</div>
@endsection