routes/web.php
<?php

use Illuminate\Support\Facades\Route;
//use Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
//Route::resource('clients', 'ClientController');
// GET/clients, mapped to the index() method,
// GET /clients/create, mapped to the create() method,
// POST /clients, mapped to the store() method,
// GET /clients/{id}, mapped to the show() method,
// GET /clients/{id}/edit, mapped to the edit() method,
// PUT/PATCH /clients/{id}, mapped to the update() method,
// DELETE /clients/{id}, mapped to the destroy() method.
*/
// ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
// Routes for "SUPERADMIN" user Role
// ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
    Route::group(['middleware' => 'auth'], function () {
        Route::get('dashboard', function () { 
            $userRole = Auth::user()->getRole();
            if($userRole == 'superadmin'){
                return redirect('home');
            } else if($userRole == 'admin') {
                return redirect('admin/home');
            } else if($userRole == 'doctor') {
                return redirect('doctor/home');
            } else {
                return redirect('/home');
            }
        });
        // ROUTES for SUPERADMIN
        Route::group(['middleware' => 'role:superadmin'], function () {
            // DASHBOARD
                Route::get('/home', 'HomeController@index')->name('home');
            // Languages
                Route::group(['prefix'=>'configs'], function () {
                    Route::resource('langs', 'LangController');
                });
            // Files
                Route::group(['prefix'=>'configs'], function () {
                    Route::resource('files', 'FileController')->only(['index','edit','update']);
                });
            // Doctor's Services Type
                Route::get('/users/stypes', 'StypeController@index')->name('stypes.index');
                Route::get('/users/stypes/create', 'StypeController@create')->name('stypes.create');
                Route::post('/users/stypes', 'StypeController@store')->name('stypes.store');
                Route::get('/users/stypes/{id}', 'StypeController@show')->name('stypes.show');
                Route::get('/users/stypes/{id}/edit', 'StypeController@edit')->name('stypes.edit');
                Route::put('/users/stypes/{id}', 'StypeController@update')->name('stypes.update');
                Route::patch('/users/stypes/{id}', 'StypeController@update')->name('stypes.update');
                Route::delete('/users/stypes/{id}', 'StypeController@destroy')->name('stypes.destroy');
            // USERS
                Route::get('/users/roles', 'UserController@userRoles')->name('List of Roles');
                Route::post('/users/{id}/trash', 'UserController@trash');
                Route::post('/users/{id}/restore', 'UserController@restore');
                Route::get('/users/createdoc', 'UserController@createdoc')->name('users.createdoc');
                Route::post('/usersdoc', 'UserController@storedoc')->name('users.storedoc');
                Route::get('/usersdoc/{id}/edit', 'UserController@editdoc')->name('users.editdoc');
                Route::put('/usersdoc/{id}', 'UserController@updatedoc')->name('users.updatedoc');
                Route::patch('/usersdoc/{id}', 'UserController@updatedoc')->name('users.updatedoc');
                Route::get('/usersdoc', 'UserController@indexdoc')->name('users.indexdoc');
                Route::resource('users', 'UserController');
            // CLIENTS
                Route::resource('clients', 'ClientController');
            // CATEGORIES
                Route::resource('tags', 'TagController');
            
            // CONTENTS 
                // IDE - GDE
                Route::get('/contents/ide', 'ContentController@ide');
                Route::post('/contents/ide', 'ContentController@ide_store');
                Route::get('/contents/gde', 'ContentController@gde');
                Route::post('/contents/gde', 'ContentController@gde_store');
                // Author
                Route::get('/contents/authors', 'AuthorController@index')->name('authors.index');
                Route::get('/contents/authors/create', 'AuthorController@create')->name('authors.create');
                Route::post('/contents/authors', 'AuthorController@store')->name('authors.store');
                Route::get('/contents/authors/{id}', 'AuthorController@show')->name('authors.show');
                Route::get('/contents/authors/{id}/edit', 'AuthorController@edit')->name('authors.edit');
                Route::put('/contents/authors/{id}', 'AuthorController@update')->name('authors.update');
                Route::patch('/contents/authors/{id}', 'AuthorController@update')->name('authors.update');
                Route::delete('/contents/authors/{id}', 'AuthorController@destroy')->name('authors.destroy');
                // Product
                Route::get('/contents/products', 'ProductController@index')->name('products.index');
                Route::get('/contents/products/create', 'ProductController@create')->name('products.create');
                Route::post('/contents/products', 'ProductController@store')->name('products.store');
                Route::get('/contents/products/{id}', 'ProductController@show')->name('products.show');
                Route::get('/contents/products/{id}/edit', 'ProductController@edit')->name('products.edit');
                Route::put('/contents/products/{id}', 'ProductController@update')->name('products.update');
                Route::patch('/contents/products/{id}', 'ProductController@update')->name('products.update');
                Route::delete('/contents/products/{id}', 'ProductController@destroy')->name('products.destroy');
                Route::resource('contents', 'ContentController');
            // CPAGES
                // Sections
                Route::get('/cpages/csections', 'CsectionController@index')->name('csections.index');
                Route::get('/cpages/csections/create', 'CsectionController@create')->name('csections.create');
                Route::post('/cpages/csections', 'CsectionController@store')->name('csections.store');
                Route::get('/cpages/csections/{id}', 'CsectionController@show')->name('csections.show');
                Route::get('/cpages/csections/{id}/edit', 'CsectionController@edit')->name('csections.edit');
                Route::put('/cpages/csections/{id}', 'CsectionController@update')->name('csections.update');
                Route::patch('/cpages/csections/{id}', 'CsectionController@update')->name('csections.update');
                Route::delete('/cpages/csections/{id}', 'CsectionController@destroy')->name('csections.destroy');
                Route::resource('cpages', 'CpageController');
            // BLOCKS              
                // blocks - advertisement
                Route::get('/blocks/create_advertisement', 'BlockController@create_advertisement');
                Route::post('/blocks/create_advertisement', 'BlockController@store_advertisement');
                Route::patch('/blocks/{id}/edit_advertisement', 'BlockController@update_advertisement');

                // blocks - videos
                Route::get('/blocks/create_video', 'BlockController@create_video');
                Route::post('/blocks/create_video', 'BlockController@store_video');
                Route::patch('/blocks/{id}/edit_video', 'BlockController@update_video');

                // blocks - text
                Route::get('/blocks/create_text', 'BlockController@create_text');
                Route::post('/blocks/create_text', 'BlockController@store_text');
                Route::patch('/blocks/{id}/edit_text', 'BlockController@update_text');

                // blocks - qrcode
                Route::get('/blocks/create_qrcode', 'BlockController@create_qrcode');
                Route::post('/blocks/create_qrcode', 'BlockController@store_qrcode');
                Route::patch('/blocks/{id}/edit_qrcode', 'BlockController@update_qrcode');

                // GLOBAL
                Route::get('/blocks', 'BlockController@index')->name('List of Blocks');
                Route::get('/blocks/{id}', 'BlockController@show');
                Route::get('/blocks/{id}/edit', 'BlockController@edit');
                Route::delete('/blocks/{id}', 'BlockController@destroy');

            // DOCTORS
                Route::post('/doctors/{id}/trash', 'DoctorController@trash');
                Route::resource('doctors', 'DoctorController')->except(['create','store']);               
            
        });
        // ROUTES for ADMIN
        Route::group(['prefix'=>'admin','middleware' => 'role:admin'], function () {
            // DASHBOARD
                Route::get('/home', 'HomeController@index')->name('home');
            // CLIENT
                Route::get('/clients/{id}', 'ClientController@admin_client_detail');
            // CATEGORIES
                Route::resource('tags', 'TagController');  
            // CONTENTS
                Route::resource('contents', 'ContentController');  
            // DOCTORS
                Route::post('/doctors/{id}/trash', 'DoctorController@trash');
                Route::resource('doctors', 'DoctorController')->except(['create','store']);
        });
        // ROUTES for DOCTOR
        Route::group(['prefix'=>'doctor', 'middleware' => 'role:doctor'], function () {
                // DASHBOARD
                Route::get('/home', 'HomeController@index')->name('home');
                // Update Profile

app/User.php
<?php

namespace App;
use App\Client;
use App\Tag;
use Laravel\Passport\HasApiTokens;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use App\Permissions\HasPermissionsTrait;

class User extends Authenticatable
{
    use HasApiTokens, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','full_name','last_login_at','last_login_ip','status','user_brief','contact_number',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    use HasPermissionsTrait; //Import The Trait

    public function clients() {
        return $this->belongsToMany(Client::class,'users_clients');
    }

    public function doctors() {
        return $this->belongsToMany(Doctor::class,'users_doctors');
    }

    public function profile(){
        return $this->hasOne(Profile::class);
    }

    public function stypes() {
        return $this->belongsToMany(Stype::class,'users_stypes');
    }

    public function langs() {
        return $this->belongsToMany(Lang::class,'users_langs')->withPivot('doc_full_name', 'doc_title', 'doc_bg_image', 'doc_profile_video', 'doc_picture', 'doc_bio');
    }

    public static function allDoctors() {
        $condition = [];
        $condition[] = ['is_deleted','=','0'];
        $query = User::where($condition);
        $query = $query->whereHas('roles', function ($q) {
            return $q->where('id', '3'); // 3 is for Doctor User Role
        });
        $query = $query->join('profiles', 'users.id', '=', 'profiles.user_id')->select('users.*', 'profiles.*');
        return $query->get();
    }
    // Fetch all user's Full Name
    // Return Array
    public static function allProfilesByUid() {
        $condition = [];
        $condition[] = ['is_deleted','=','0'];
        $query = User::where($condition);
        $query = $query->join('profiles', 'users.id', '=', 'profiles.user_id')->select('users.id', 'profiles.full_name');
        $result = $query->get()->toArray();
        $profilesAry = [];
        foreach($result as $k=>$v) {
            $profilesAry[$v['id']] = $v['full_name'];
        }
        return $profilesAry;
    }

    // Method to get clients of Current User
    public static function getClients() {
        $role = auth()->user()->roles()->first()->toArray();
        if($role['slug'] == 'superadmin') {
            return Client::all()->toArray();
        } else if($role['slug'] == 'admin') {
            return auth()->user()->clients()->get()->toArray();
        }  else if($role['slug'] == 'doctor') {
            return auth()->user()->clients()->get()->toArray();
        } else {
            return [];
        }
    }
    // Method to get role of Current User
    public static function getProfile() {
        $profile = auth()->user()->profile()->first()->toArray();
        return $profile;
    }
    // Method to get role of Current User
    public static function getRole() {
        $role = auth()->user()->roles()->first()->toArray();
        return $role['slug'];
    }
    // Method to get tags of Current User
    public static function getTags() {
        $role = auth()->user()->roles()->first()->toArray();
        if($role['slug'] == 'superadmin') {
            return Tag::all()->toArray();
        } else if($role['slug'] == 'admin') {
            $userClientIds = [];
            $userClients = auth()->user()->clients()->get()->toArray();
            foreach($userClients as $k=>$v) {
                $userClientIds[] = $v['id'];
            }
            $cond = [];
            $tagQuery = Tag::where($cond)->whereHas('clients', function ($q) use ($userClientIds) {
                return $q->whereIn('id', $userClientIds ); // Check in assigned Clients of current user
            });
            return $tagQuery->get()->toArray();
            //return [];
        } else {
            return [];
        }
    }
}

resources/views/users/create.blade.php
@extends('layouts.dashboard')
<?php
$service_types = ['ide' => 'Interactive Discussion', 'sd' => 'Second Opinion'];
?>
@section('content')
<div class="page-heading"><h3>Add User - Admin </h3></div>
@include('flash-message')
<style type="text/css">
    h4.subheading{border-bottom: 2px solid #F4D03F;color: #333;font-size: 20px;margin-bottom: 20px;background: #ECDDA199;padding: 6px;}
</style>

<div class="col-md-8 col-md-offset-2 users-create-page superusers form large-9 medium-8 columns content">
	<section class="panel">
		<div class="panel-body">
            <form method="POST"  enctype="multipart/form-data" action="{{ route('users.store') }}">
            @csrf
                <div class="row">
                    <div class="col-md-12">
                        <h4 class="subheading">Account Information</h4>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="required">Username</label><br />
                            <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>
                            @error('name')
                                <span class="invalid-feedback msg-error" role="alert"><i class="fa fa-exclamation-triangle"></i> {{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="required">Email</label><br />
                            <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email">
                            @error('email')
                                <span class="invalid-feedback msg-error" role="alert"><i class="fa fa-exclamation-triangle"></i> {{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="required">Password</label><br />
                            <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="new-password">
                            @error('password')
                                <span class="invalid-feedback msg-error" role="alert"><i class="fa fa-exclamation-triangle"></i> {{ $message }}</span>
                            @enderror
                        </div>
                    </div>               
                    <div class="col-lg-6">
                        <div class="form-group required">
                            <label class="required">Confirm Password</label><br />
                            <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required autocomplete="new-password">
                        </div>
                    </div>
                </div>
                 <div class="row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="required">User Role</label><br />
                            <select class="form-control @error('role') is-invalid @enderror" name="role" id="user-roles" required autocomplete="role">
                                <?php foreach($roles as $k=>$v) { ?>
                                <option {{ old('role')==$k ? 'selected' : ''  }} value="<?= $k ?>"><?= $v ?></option>
                                <?php } ?>
                            </select>
                            @error('role')
                                <span class="invalid-feedback msg-error" role="alert"><i class="fa fa-exclamation-triangle"></i> {{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="required">Status</label><br />
                            <select class="form-control @error('status') is-invalid @enderror" name="status" id="status" required>
                                <?php foreach($status as $k=>$v) { ?>
                                <option value="<?= $k ?>"><?= $v ?></option>
                                <?php } ?>
                            </select>
                            @error('status')
                                <span class="invalid-feedback msg-error" role="alert"><i class="fa fa-exclamation-triangle"></i> {{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        @php
                            $old_role_client_display = (old('role') == '2') ? 'display_block' : 'display_none';
                        @endphp
                        <div id="form-field-clients" class="form-checkbox-wrapper  {{ $old_role_client_display }}">
                            <label class="required">Clients</label><br />
                            <div id="create_user_client_listing_form_group" class="form-control">
                                <?php foreach($clients as $k=>$v) { ?>
                                    <div class="form-item">
                                    <input id="client_<?= $k ?>" type="checkbox" class="form-control @error('client') is-invalid @enderror" name="client[]" value="<?= $k ?>" autocomplete="client">
                                    <label for="client_<?= $k ?>"><?= $v ?></label>
                                    </div>
                                <?php } ?>
                            </div>
                            <span class="help-text">( Choose minimum one client for "Admin" User Role )</span>
                            @error('client')
                                <span class="invalid-feedback msg-error" role="alert"><i class="fa fa-exclamation-triangle"></i> {{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                </div>
               
                <div class="row">
                    <div class="col-md-12">
                        <h4 class="subheading">Profile Information</h4>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="required">Full Name</label><br />
                            <input id="full_name" type="text" class="form-control @error('full_name') is-invalid @enderror" name="full_name" value="{{ old('full_name') }}" required autocomplete="full_name" autofocus>
                            @error('full_name')
                                <span class="invalid-feedback msg-error" role="alert"><i class="fa fa-exclamation-triangle"></i> {{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="required">Title</label><br />
                            <input id="title" type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('title') }}" required autocomplete="title" autofocus>
                            @error('title')
                                <span class="invalid-feedback msg-error" role="alert"><i class="fa fa-exclamation-triangle"></i> {{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6">       
                        <div class="form-group">
                            <label >Profile Picture</label><br />
                            <input id="picture" type="file" class="form-control @error('picture') is-invalid @enderror" name="picture" value="{{ old('picture') }}" autocomplete="picture" autofocus>
                            @error('picture')
                                <span class="invalid-feedback msg-error" role="alert"><i class="fa fa-exclamation-triangle"></i> {{ $message }}</span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label >Contact Number</label><br />
                            <input id="contact_number" type="text" class="form-control @error('contact_number') is-invalid @enderror" name="contact_number" value="{{ old('contact_number') }}" autocomplete="contact_number">
                            @error('contact_number')
                                <span class="invalid-feedback msg-error" role="alert"><i class="fa fa-exclamation-triangle"></i> {{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                    <div class="col-lg-6">
                        
                        <div class="form-group">
                            <label>Bio</label><br />
                            <textarea  id="user_brief" name="user_brief" class="form-control @error('user_brief') is-invalid @enderror" cols="5" rows="4">{{ old('user_brief') }}</textarea>
                            @error('user_brief')
                                <span class="invalid-feedback msg-error" role="alert"><i class="fa fa-exclamation-triangle"></i> {{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                </div>
                
                <br />
                <div class="row">
                    <div class="col-lg-12 text-center">
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">{{ __('Add User') }}</button>
                        </div>
                    </div>
                </div>
            </form>
		</div>
	</section>
</div>
@endsection

resources/views/users/edit_profile.blade.php
@extends('layouts.dashboard')

@section('content')
<div class="page-heading"><h3>Update Profile</h3></div>
@include('flash-message')
<?php 
$role = auth()->user()->getRole();
$role_segment = ($role == 'admin')?'/admin':'';
$base_url  = URL::to('/').$role_segment;
?>
<style type="text/css">
    .users-edit-page form .form-checkbox-wrapper #create_user_client_listing_form_group{height: 156px;}
    h4.subheading{border-bottom: 2px solid #F4D03F;color: #333;font-size: 20px;margin-bottom: 20px;background: #ECDDA199;padding: 6px;}
    .form-item-display p{background: #eee;margin:0px;border: 1px solid #ccc;padding: 6px;border-radius: 5px;}
    .existing-attachment{text-align:center;background: #ECDDA199; height: 76px; display: block; width: 50px; margin-top: 5px; border: 1px solid #F4D03F;}
    .existing-attachment a{font-size: 10px;line-height: 0px;color: #333;text-decoration: underline;}
    .panel-header{ padding: 10px; }
</style>
<div class="col-md-8 col-md-offset-2 users-edit-page form large-9 medium-8 columns content">
	<section class="panel">
		<div class="panel-body">
            <form method="post" enctype="multipart/form-data" action="{{ route('update_profile') }}">
            @csrf
                <div class="row">
                    <div class="col-lg-6">
                        <div class="form-group form-item-display">
                            <label>Username</label>
                            <p>{{ $user['name'] }}</p>
                            <span class="help-text">( Cannot update username once created. )</span>
                        </div>
                        <div class="form-group">
                            <label class="required">Full Name</label><br />
                            <input id="full_name" type="text" class="form-control @error('full_name') is-invalid @enderror" name="full_name" required autocomplete="full_name" value="{{ $user['profile']['full_name'] }}">
                            @error('full_name')
                                <span class="invalid-feedback msg-error" role="alert"><i class="fa fa-exclamation-triangle"></i> {{ $message }}</span>
                            @enderror
                        </div> 
                        
                        <div class="form-group">
                            <label >Contact Number</label><br />
                            <input id="contact_number" type="text" class="form-control @error('contact_number') is-invalid @enderror" name="contact_number" autocomplete="contact_number" value="{{ $user['profile']['contact_number'] }}" >
                            @error('full_name')
                                <span class="invalid-feedback msg-error" role="alert"><i class="fa fa-exclamation-triangle"></i> {{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group form-item-display">
                            <label>Email</label><br />
                            <p>{{ $user['email'] }}</p>
                            <span class="help-text">( Cannot update email once created. )</span>
                        </div>
                        <div class="form-group">
                            <label class="required">Title</label><br />
                            <input id="title" type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ $user['profile']['title'] }}" required autocomplete="title">
                            @error('title')
                                <span class="invalid-feedback msg-error" role="alert"><i class="fa fa-exclamation-triangle"></i> {{ $message }}</span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <?php if(!empty($user['profile']['picture'])) { ?>
                                <div class="col-md-2 existing-attachment">
                                <a href="{{ $user['profile']['picture'] }}" target="blank">Link to Image</a>
                                </div>
                                <div class="col-md-10">
                            <?php } ?>
                                <label >Profile Picture</label><br />
                                <input accept=".jpg, .png, .jpeg" id="picture" type="file" class="form-control @error('picture') is-invalid @enderror" name="picture" value="{{ old('picture') }}" autocomplete="picture" >
                                @error('picture')
                                    <span class="invalid-feedback msg-error" role="alert"><i class="fa fa-exclamation-triangle"></i> {{ $message }}</span>
                                @enderror
                            <?php if(!empty($user['profile']['picture'])) { ?>
                                <div class=""><input value="1" type="checkbox" name="remove_picture" id="remove_picture"/><label for="remove_picture">&nbsp;Remove Picture</label></div>
                                </div>
                            <?php } ?>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2">                      
                        <div class="form-group">
                            <label class="required">Doctor Bio</label><br />
                            <textarea required id="user_brief" name="user_brief" class="form-control @error('user_brief') is-invalid @enderror" cols="5" rows="8">{{ $user['profile']['bio'] }}</textarea>
                            @error('user_brief')
                                <span class="invalid-feedback msg-error" role="alert"><i class="fa fa-exclamation-triangle"></i> {{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-lg-12 text-center">
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">{{ __('Update User') }}</button>
                        </div>
                    </div>
                </div>
            </form>
		</div>
	</section>
</div>
@endsection