routes/web.php
<?php

use Illuminate\Support\Facades\Route;
//use Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
//Route::resource('clients', 'ClientController');
// GET/clients, mapped to the index() method,
// GET /clients/create, mapped to the create() method,
// POST /clients, mapped to the store() method,
// GET /clients/{id}, mapped to the show() method,
// GET /clients/{id}/edit, mapped to the edit() method,
// PUT/PATCH /clients/{id}, mapped to the update() method,
// DELETE /clients/{id}, mapped to the destroy() method.
*/
// ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
// Routes for "SUPERADMIN" user Role
// ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
    Route::group(['middleware' => 'auth'], function () {
        Route::get('dashboard', function () { 
            $userRole = Auth::user()->getRole();
            if($userRole == 'superadmin'){
                return redirect('home');
            } else if($userRole == 'admin') {
                return redirect('admin/home');
            } else if($userRole == 'doctor') {
                return redirect('doctor/home');
            } else {
                return redirect('/home');
            }
        });
        // ROUTES for SUPERADMIN
        Route::group(['middleware' => 'role:superadmin'], function () {
            // DASHBOARD
                Route::get('/home', 'HomeController@index')->name('home');
            // Languages
                Route::group(['prefix'=>'configs'], function () {
                    Route::resource('langs', 'LangController');
                });
            // Files
                Route::group(['prefix'=>'configs'], function () {
                    Route::resource('files', 'FileController')->only(['index','edit','update']);
                });
            // Doctor's Services Type
                Route::get('/users/stypes', 'StypeController@index')->name('stypes.index');
                Route::get('/users/stypes/create', 'StypeController@create')->name('stypes.create');
                Route::post('/users/stypes', 'StypeController@store')->name('stypes.store');
                Route::get('/users/stypes/{id}', 'StypeController@show')->name('stypes.show');
                Route::get('/users/stypes/{id}/edit', 'StypeController@edit')->name('stypes.edit');
                Route::put('/users/stypes/{id}', 'StypeController@update')->name('stypes.update');
                Route::patch('/users/stypes/{id}', 'StypeController@update')->name('stypes.update');
                Route::delete('/users/stypes/{id}', 'StypeController@destroy')->name('stypes.destroy');
            // USERS
                Route::get('/users/roles', 'UserController@userRoles')->name('List of Roles');
                Route::post('/users/{id}/trash', 'UserController@trash');
                Route::post('/users/{id}/restore', 'UserController@restore');
                Route::get('/users/createdoc', 'UserController@createdoc')->name('users.createdoc');
                Route::post('/usersdoc', 'UserController@storedoc')->name('users.storedoc');
                Route::get('/usersdoc/{id}/edit', 'UserController@editdoc')->name('users.editdoc');
                Route::put('/usersdoc/{id}', 'UserController@updatedoc')->name('users.updatedoc');
                Route::patch('/usersdoc/{id}', 'UserController@updatedoc')->name('users.updatedoc');
                Route::get('/usersdoc', 'UserController@indexdoc')->name('users.indexdoc');
                Route::resource('users', 'UserController');
            // CLIENTS
                Route::resource('clients', 'ClientController');
            // CATEGORIES
                Route::resource('tags', 'TagController');
            
            // CONTENTS 
                // IDE - GDE
                Route::get('/contents/ide', 'ContentController@ide');
                Route::post('/contents/ide', 'ContentController@ide_store');
                Route::get('/contents/gde', 'ContentController@gde');
                Route::post('/contents/gde', 'ContentController@gde_store');
                // Author
                Route::get('/contents/authors', 'AuthorController@index')->name('authors.index');
                Route::get('/contents/authors/create', 'AuthorController@create')->name('authors.create');
                Route::post('/contents/authors', 'AuthorController@store')->name('authors.store');
                Route::get('/contents/authors/{id}', 'AuthorController@show')->name('authors.show');
                Route::get('/contents/authors/{id}/edit', 'AuthorController@edit')->name('authors.edit');
                Route::put('/contents/authors/{id}', 'AuthorController@update')->name('authors.update');
                Route::patch('/contents/authors/{id}', 'AuthorController@update')->name('authors.update');
                Route::delete('/contents/authors/{id}', 'AuthorController@destroy')->name('authors.destroy');
                // Product
                Route::get('/contents/products', 'ProductController@index')->name('products.index');
                Route::get('/contents/products/create', 'ProductController@create')->name('products.create');
                Route::post('/contents/products', 'ProductController@store')->name('products.store');
                Route::get('/contents/products/{id}', 'ProductController@show')->name('products.show');
                Route::get('/contents/products/{id}/edit', 'ProductController@edit')->name('products.edit');
                Route::put('/contents/products/{id}', 'ProductController@update')->name('products.update');
                Route::patch('/contents/products/{id}', 'ProductController@update')->name('products.update');
                Route::delete('/contents/products/{id}', 'ProductController@destroy')->name('products.destroy');
                Route::resource('contents', 'ContentController');
            // CPAGES
                // Sections
                Route::get('/cpages/csections', 'CsectionController@index')->name('csections.index');
                Route::get('/cpages/csections/create', 'CsectionController@create')->name('csections.create');
                Route::post('/cpages/csections', 'CsectionController@store')->name('csections.store');
                Route::get('/cpages/csections/{id}', 'CsectionController@show')->name('csections.show');
                Route::get('/cpages/csections/{id}/edit', 'CsectionController@edit')->name('csections.edit');
                Route::put('/cpages/csections/{id}', 'CsectionController@update')->name('csections.update');
                Route::patch('/cpages/csections/{id}', 'CsectionController@update')->name('csections.update');
                Route::delete('/cpages/csections/{id}', 'CsectionController@destroy')->name('csections.destroy');
                Route::resource('cpages', 'CpageController');
            // BLOCKS              
                // blocks - advertisement
                Route::get('/blocks/create_advertisement', 'BlockController@create_advertisement');
                Route::post('/blocks/create_advertisement', 'BlockController@store_advertisement');
                Route::patch('/blocks/{id}/edit_advertisement', 'BlockController@update_advertisement');

                // blocks - videos
                Route::get('/blocks/create_video', 'BlockController@create_video');
                Route::post('/blocks/create_video', 'BlockController@store_video');
                Route::patch('/blocks/{id}/edit_video', 'BlockController@update_video');

                // blocks - text
                Route::get('/blocks/create_text', 'BlockController@create_text');
                Route::post('/blocks/create_text', 'BlockController@store_text');
                Route::patch('/blocks/{id}/edit_text', 'BlockController@update_text');

                // blocks - qrcode
                Route::get('/blocks/create_qrcode', 'BlockController@create_qrcode');
                Route::post('/blocks/create_qrcode', 'BlockController@store_qrcode');
                Route::patch('/blocks/{id}/edit_qrcode', 'BlockController@update_qrcode');

                // GLOBAL
                Route::get('/blocks', 'BlockController@index')->name('List of Blocks');
                Route::get('/blocks/{id}', 'BlockController@show');
                Route::get('/blocks/{id}/edit', 'BlockController@edit');
                Route::delete('/blocks/{id}', 'BlockController@destroy');

            // DOCTORS
                Route::post('/doctors/{id}/trash', 'DoctorController@trash');
                Route::resource('doctors', 'DoctorController')->except(['create','store']);               
            
        });
        // ROUTES for ADMIN
        Route::group(['prefix'=>'admin','middleware' => 'role:admin'], function () {
            // DASHBOARD
                Route::get('/home', 'HomeController@index')->name('home');
            // CLIENT
                Route::get('/clients/{id}', 'ClientController@admin_client_detail');
            // CATEGORIES
                Route::resource('tags', 'TagController');  
            // CONTENTS
                Route::resource('contents', 'ContentController');  
            // DOCTORS
                Route::post('/doctors/{id}/trash', 'DoctorController@trash');
                Route::resource('doctors', 'DoctorController')->except(['create','store']);
        });
        // ROUTES for DOCTOR
        Route::group(['prefix'=>'doctor', 'middleware' => 'role:doctor'], function () {
                // DASHBOARD
                Route::get('/home', 'HomeController@index')->name('home');
                // Update Profile

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'description',
    ];

     public function users() {
             return $this->belongsToMany(User::class,'users_clients');
            
     }
     public function doctors() {
        return $this->belongsToMany(Doctor::class,'clients_doctors');
     }

     public function cpages() {
      return $this->belongsToMany(Cpage::class,'clients_cpages');
    }

    public function cpagesbyptype($ptyp) {
      return $this->belongsToMany(Cpage::class,'clients_cpages')->where('ptype',$ptyp);
    }

     public function doctorUsers() {
        $result = User::allDoctors()->toArray();
        $allDoctors = [];
        foreach($result as $k=>$v){
            $allDoctors[] = $v['id'];
        }       
        return $this->belongsToMany(User::class,'users_clients')->whereIn('user_id',$allDoctors);
     }
     
     public function tags() {
        return $this->belongsToMany(Tag::class,'tags_clients');
     }

     public function langs() {
      return $this->belongsToMany(Lang::class,'clients_langs');
      }

     // Helper Methods
     public static function getAllClients(){
        $allClients = Client::all('id','name')->toArray();
        $clients = [];
        foreach($allClients as $k=>$v){
            $clients[$v['id']] = $v['name'];
        }
        return $clients;
     }
}

resources/views/clients/create.blade.php
@extends('layouts.dashboard')

@section('content')
<style type="text/css">
    #create_client_doctor_listing_form_group{ height: 100px; overflow-y: scroll; }
    #create_client_doctor_listing_form_group .form-item{display: flex;}
    #create_client_doctor_listing_form_group .form-item input {width: auto; height: auto; margin-right: 5px;}
    #create_client_doctor_listing_form_group .form-item label{font-weight: normal;}

    #create_client_tag_listing_form_group{ height: 100px; overflow-y: scroll; }
    #create_client_tag_listing_form_group .form-item{display: flex;}
    #create_client_tag_listing_form_group .form-item input {width: auto; height: auto; margin-right: 5px;}
    #create_client_tag_listing_form_group .form-item label{font-weight: normal;}
    #configure_langs_listing_form_group{ height: 100px; overflow-y: scroll; }
    #configure_langs_listing_form_group .form-item{display: flex;}
    #configure_langs_listing_form_group .form-item input {width: auto; height: auto; margin-right: 5px;}
    #configure_langs_listing_form_group .form-item label{font-weight: normal;}
</style>
<div class="page-heading"><h3>Add Client</h3></div>
@include('flash-message')
<div class="col-md-8 col-md-offset-2 clients-create-page clients form large-9 medium-8 columns content">
	<section class="panel">
		<div class="panel-body">
            <form method="POST" action="{{ route('clients.store') }}">
            @csrf
                <div class="row">
                    <div class="col-lg-6 col-lg-offset-3">
                        <div class="form-group">
                            <label class="required">Client Name</label><br />
                            <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>
                            @error('name')
                                <span class="invalid-feedback msg-error" role="alert"><i class="fa fa-exclamation-triangle"></i> {{ $message }}</span>
                            @enderror
                        </div>
                        <div id="form-field-langs" class="form-group form-checkbox-wrapper">
                            <label class="required">Client's Languages</label><br />
                            <div id="configure_langs_listing_form_group" class="form-control">
                                <?php foreach($langs as $k=>$v) { ?>
                                    <div class="form-item">
                                    <input 
                                    <?= ($v['is_freeze'] == '1')?'disabled checked':''?> 
                                    id="lang_<?= $v['id'] ?>" type="checkbox" class="form-control @error('lang') is-invalid @enderror" name="clangs[]" value="<?= $v['id'] ?>">
                                    <label for="lang_<?= $v['id'] ?>"><?= $v['name'] ?> ( <?= $v['code'] ?> )</label>
                                    </div>
                                <?php } ?>
                            </div>
                            <span class="help-text">( Only enabled languages will display in client. )</span>
                            @error('clangs')
                                <span class="invalid-feedback msg-error" role="alert"><i class="fa fa-exclamation-triangle"></i> {{ $message }}</span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label class="required">Description</label><br />
                            <textarea  id="description" required name="description" class="form-control @error('description') is-invalid @enderror" cols="5" rows="8">{{ old('description') }}</textarea>
                            @error('description')
                                <span class="invalid-feedback msg-error" role="alert"><i class="fa fa-exclamation-triangle"></i> {{ $message }}</span>
                            @enderror
                        </div>
                        
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-lg-12 text-center">
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">{{ __('Save Client') }}</button>
                        </div>
                    </div>
                </div>
            </form>
		</div>
	</section>
</div>
@endsection

resources/views/clients/edit.blade.php
@extends('layouts.dashboard')

@section('content')
<style type="text/css">
    #create_client_doctor_listing_form_group{ height: 100px; overflow-y: scroll; }
    #create_client_doctor_listing_form_group .form-item{display: flex;}
    #create_client_doctor_listing_form_group .form-item input {width: auto; height: auto; margin-right: 5px;}
    #create_client_doctor_listing_form_group .form-item label{font-weight: normal;}
    #create_client_tag_listing_form_group{ height: 100px; overflow-y: scroll; }
    #create_client_tag_listing_form_group .form-item{display: flex;}
    #create_client_tag_listing_form_group .form-item input {width: auto; height: auto; margin-right: 5px;}
    #create_client_tag_listing_form_group .form-item label{font-weight: normal;}
    /* Language Field */
    #configure_langs_listing_form_group{ height: 100px; overflow-y: scroll; }
    #configure_langs_listing_form_group .form-item{display: flex;}
    #configure_langs_listing_form_group .form-item input {width: auto; height: auto; margin-right: 5px;}
    #configure_langs_listing_form_group .form-item label{font-weight: normal;}
</style>
<div class="page-heading"><h3>Update Client</h3></div>
@include('flash-message')
<div class="col-md-8 col-md-offset-2 clients-create-page clients form large-9 medium-8 columns content">
	<section class="panel">
		<div class="panel-body">
            <form method="post" action="{{ route('clients.update', $client['client']['id']) }}">
            @method('PATCH') 
            @csrf
                <div class="row">
                    <div class="col-lg-6 col-lg-offset-3">
                        <div class="form-group">
                            <label class="required">Client Name</label><br />
                            <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" required autocomplete="name" autofocus value="{{ $client['client']['name'] }}">
                            @error('name')
                                <span class="invalid-feedback msg-error" role="alert"><i class="fa fa-exclamation-triangle"></i> {{ $message }}</span>
                            @enderror
                        </div>
                        <div id="form-field-langs" class="form-group form-checkbox-wrapper">
                            <label class="required">Client's Languages</label><br />
                            <div id="configure_langs_listing_form_group" class="form-control">
                                <?php foreach($langs as $k=>$v) { ?>
                                    <div class="form-item">
                                    <input 
                                    <?= (in_array($v['id'], $client['langs']))?'checked ':''?>
                                    <?= ($v['is_freeze'] == '1')?'disabled checked ':''?> 
                                    id="lang_<?= $v['id'] ?>" type="checkbox" class="form-control @error('lang') is-invalid @enderror" name="clangs[]" value="<?= $v['id'] ?>">
                                    <label for="lang_<?= $v['id'] ?>"><?= $v['name'] ?> ( <?= $v['code'] ?> )</label>
                                    </div>
                                <?php } ?>
                            </div>
                            <span class="help-text">( Only enabled languages will display in client. )</span>
                            @error('clangs')
                                <span class="invalid-feedback msg-error" role="alert"><i class="fa fa-exclamation-triangle"></i> {{ $message }}</span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label class="required" >Description</label><br />
                            <textarea required id="description" name="description" class="form-control @error('description') is-invalid @enderror" cols="5" rows="8">{{ $client['client']['description'] }}</textarea>
                            @error('description')
                                <span class="invalid-feedback msg-error" role="alert"><i class="fa fa-exclamation-triangle"></i> {{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-lg-12 text-center">
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">{{ __('Update Client') }}</button>
                        </div>
                    </div>
                </div>
            </form>
		</div>
	</section>
</div>
@endsection

resources/views/clients/index.blade.php
@extends('layouts.dashboard')

@section('content')
<div class="page-heading"><h3>List of Clients</h3></div>
@include('flash-message')
<?php 
$base_url  = URL::to('/');
?>
<style type="text/css">
    table tr td.client-doctor-count-col span{display: block; text-align: center;}
    table tr td.client-tags-count-col span{display: block; text-align: center;}
</style>
<div class="clients form large-9 medium-8 columns content">
	<section class="panel">
        <div class="panel-heading ">
            <div class="row clients_filters_wrapper bg-secondary">
                <form method="get" id="form_clients_filter" >
                    <div class="col-md-3 form-group">
                        <label>Client Name</label><br />
                        <input class="form-control" type="text" name="cnm" id="clients-filter-cnm" value="<?= (!empty($qry['cnm']))?$qry['cnm']:'' ?>" /> 
                    </div>
                    <div class="col-md-2 form-group">
                        <label>Doctor</label><br />
                        <select class="form-control @error('did') is-invalid @enderror" name="did" id="did">
                            <option value="">- Select One -</option>
                            @foreach($doctors as $k=>$v)
                                <option <?php if((!empty($qry['did'])) && ($qry['did'] == $v['id'])){ echo "selected"; } ?> value="{{ $v['id'] }}">{{ $v['full_name'] }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="col-md-2 form-group">
                        <label>Category</label><br />
                        <select class="form-control @error('tid') is-invalid @enderror" name="tid" id="tid">
                            <option value="">- Select One -</option>
                            @foreach($tags as $k=>$v)
                                <option <?php if((!empty($qry['tid'])) && ($qry['tid'] == $v['id'])){ echo "selected"; } ?> value="{{ $v['id'] }}">{{ $v['name'] }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="col-md-2 form-group">
                        <label>Languages</label><br />
                        <select class="form-control @error('tid') is-invalid @enderror" name="lng" id="lng">
                            <option value="">- Select One -</option>
                            @foreach($langs as $k=>$v)
                                <option <?php if((!empty($qry['lng'])) && ($qry['lng'] == $v['id'])){ echo "selected"; } ?> value="{{ $v['id'] }}">{{ $v['name'] }} ( {{ $v['code'] }} )</option>
                            @endforeach
                        </select>
                    </div>	
                    <div class="col-md-2 form-group">  
                        <label>&nbsp;</label><br />
                        <input type="submit" name="submit" value="Search" class="btn btn-primary" />
                        <a href="<?= $base_url ?>/clients" class="btn btn-secondary">Reset</a>
                    </div>	
                </form>
            </div>	
        </div>
		<div class="panel-body">
        <?php if(count($clients) > 0) { ?>
        <table class="table  table-hover general-table">
            <thead>
                <tr>
                    <th width="8%">Client Id</th>
                    <th width="15%">Client Name</th>
                    <th width="15%">Description</th>
                    <th width="15%">Languages</th>
                    <th width="10%">Doctors</th>
                    <th width="10%">Categories</th>
                    <th width="15%">Created Date</th>
                    <th width="10%">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach($clients as $client)
                <tr>
                    <td>{{ $client['id'] }}</td>
                    <td>{{ $client['name'] }}</td>
                    <td> <?php echo substr($client['description'], 0,30); ?>...   </td>
                    <td><ul>
                    <?php foreach($client['langs'] as $k=>$v ) {
                        echo '<li>'.$v['name'].' ( '.$v['code'].' )'.'</li>';
                    }  ?>
                    </ul></td>
                    <td class="client-doctor-count-col">
                        <span><strong>{{ count($client['doctors']) }}</strong></span>
                        <span>
                            <a target="_blank" href="<?= $base_url ?>/doctors?cid=<?= $client['id'] ?>" title="View Doctors under this client">[ view ]</a>
                        </span>
                    </td>
                    <td class="client-tags-count-col">
                        <span><strong>{{ count($client['tags']) }}</strong></span>
                        <span>
                            <a target="_blank" href="<?= $base_url ?>/tags?cid=<?= $client['id'] ?>" title="View Categories under this client">[ view ]</a>
                        </span>
                    </td>
                    <td>{{ date('M d, Y H:i:s',strtotime($client['created_at'])) }}</td>
                    <td class="actions">
                        <a href="<?= $base_url ?>/clients/<?= $client['id'] ?>" title="View Client"><i class="fa fa-search-plus"></i></a>&nbsp;&nbsp;
                        <a href="<?= $base_url ?>/clients/<?= $client['id'] ?>/edit" title="Edit Client"><i class="fa fa-pencil"></i></a>&nbsp;&nbsp;
                        <form name="post_client_<?= $client['id'] ?>" style="display:none;" method="post" action="{{ route('clients.destroy', $client['id']) }}" > @method('DELETE')  @csrf</form>

                        <a href="#" onclick="if (confirm(&quot;Are you sure you want to delete client <?= $client['name'] ?>?&quot;)) { document.post_client_<?= $client['id'] ?>.submit(); } event.returnValue = false; return false;" title="Delete Client"><i class="fa fa-trash-o"></i></a>
                    </td>
                </tr>
                @endforeach
            <tbody>
        </table>
        <div class="text-center">
            {{ $paginate->links() }}
        </div>
        <?php } else {
            echo '<div class="text-center">No Record Found.</div>';
        } ?>
		</div>
	</section>
</div>
@endsection

resources/views/clients/show.blade.php
@extends('layouts.dashboard')

@section('content')
<div class="page-heading"><h3>Client Detail</h3></div>
@include('flash-message')
<?php 
$base_url  = URL::to('/');
?>
<style type="text/css">
    .panel-header{ padding: 10px; }
</style>
<div class="col-md-8 col-md-offset-2 client-view-page clients form large-9 medium-8 columns content">
	<section class="panel">
        <div class="panel-header">
            <div class="row action-items">
                <div class="col-md-6 text-left">
                    <a title="Back to Client Listing" href="<?= $base_url ?>/clients" class="btn btn-primary"><i class="fa fa-backward"></i></a>
                </div>
                <div class="col-md-6 text-right">
                    <a title="Edit Client" href="<?= $base_url ?>/clients/<?=  $client['id'] ?>/edit" class="btn btn-primary"><i class="fa fa-pencil"></i></a>
                </div>
            </div>
        </div>
		<div class="panel-body">
        <?php if(count($client) > 0) { ?>
        <table class="table table-bordered superusers-view table-striped">
            <thead>
                <tr>
                    <th class="bg-primary" width="50%">KEY</th>
                    <th class="bg-primary" width="50%">VALUE</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Id</td>
                    <td><?=  $client['id'] ?></td>
                </tr>
                <tr>
                    <td>Name</td>
                    <td><?= $client['name'] ?></td>
                </tr>
                <tr>
                    <td>Description</td>
                    <td><?= $client['description'] ?></td>
                </tr>
                <tr>
                    <td>Doctors<br /><span class="help-text">( Associated with this Client )</span></td>
                    <td>
                    <?php 
                    if(count($client['doctors']) > 0 ){
                        echo "<ul>";
                        foreach($client['doctors'] as $k=>$v) { 
                        ?>
                        <li><?= $v['full_name'] ?>&nbsp;&nbsp;<a href="<?= $base_url ?>/doctors/<?= $v['id'] ?>" title="View Doctor"><i class="fa fa-user-md"></i></a></li>
                        <?php 
                        } 
                        echo "</ul>";
                    }
                    ?>
                    
                    </td>
                </tr>
                <tr>
                    <td>Categories<br /><span class="help-text">( Associated with this Client )</span></td>
                    <td>
                    <?php 
                    if(count($client['tags']) > 0 ){
                        echo "<ul>";
                        foreach($client['tags'] as $k=>$v) { 
                        ?>
                        <li><?= $v['name'] ?>&nbsp;&nbsp;<a href="<?= $base_url ?>/tags/<?= $v['id'] ?>" title="View Category"><i class="fa fa-tag"></i></a></li>
                        <?php 
                        } 
                        echo "</ul>";
                    }
                    ?>
                    
                    </td>
                </tr>
                
            </tbody>
        </table>
        <?php } else {
            echo '<div class="text-center">No Record Found.</div>';
        } ?>

		</div>
	</section>
</div>
@endsection