routes/web.php
<?php

use Illuminate\Support\Facades\Route;
//use Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
//Route::resource('clients', 'ClientController');
// GET/clients, mapped to the index() method,
// GET /clients/create, mapped to the create() method,
// POST /clients, mapped to the store() method,
// GET /clients/{id}, mapped to the show() method,
// GET /clients/{id}/edit, mapped to the edit() method,
// PUT/PATCH /clients/{id}, mapped to the update() method,
// DELETE /clients/{id}, mapped to the destroy() method.
*/
// ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
// Routes for "SUPERADMIN" user Role
// ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
    Route::group(['middleware' => 'auth'], function () {
        Route::get('dashboard', function () { 
            $userRole = Auth::user()->getRole();
            if($userRole == 'superadmin'){
                return redirect('home');
            } else if($userRole == 'admin') {
                return redirect('admin/home');
            } else if($userRole == 'doctor') {
                return redirect('doctor/home');
            } else {
                return redirect('/home');
            }
        });
        // ROUTES for SUPERADMIN
        Route::group(['middleware' => 'role:superadmin'], function () {
            // DASHBOARD
                Route::get('/home', 'HomeController@index')->name('home');
            // Languages
                Route::group(['prefix'=>'configs'], function () {
                    Route::resource('langs', 'LangController');
                });
            // Files
                Route::group(['prefix'=>'configs'], function () {
                    Route::resource('files', 'FileController')->only(['index','edit','update']);
                });
            // Doctor's Services Type
                Route::get('/users/stypes', 'StypeController@index')->name('stypes.index');
                Route::get('/users/stypes/create', 'StypeController@create')->name('stypes.create');
                Route::post('/users/stypes', 'StypeController@store')->name('stypes.store');
                Route::get('/users/stypes/{id}', 'StypeController@show')->name('stypes.show');
                Route::get('/users/stypes/{id}/edit', 'StypeController@edit')->name('stypes.edit');
                Route::put('/users/stypes/{id}', 'StypeController@update')->name('stypes.update');
                Route::patch('/users/stypes/{id}', 'StypeController@update')->name('stypes.update');
                Route::delete('/users/stypes/{id}', 'StypeController@destroy')->name('stypes.destroy');
            // USERS
                Route::get('/users/roles', 'UserController@userRoles')->name('List of Roles');
                Route::post('/users/{id}/trash', 'UserController@trash');
                Route::post('/users/{id}/restore', 'UserController@restore');
                Route::get('/users/createdoc', 'UserController@createdoc')->name('users.createdoc');
                Route::post('/usersdoc', 'UserController@storedoc')->name('users.storedoc');
                Route::get('/usersdoc/{id}/edit', 'UserController@editdoc')->name('users.editdoc');
                Route::put('/usersdoc/{id}', 'UserController@updatedoc')->name('users.updatedoc');
                Route::patch('/usersdoc/{id}', 'UserController@updatedoc')->name('users.updatedoc');
                Route::get('/usersdoc', 'UserController@indexdoc')->name('users.indexdoc');
                Route::resource('users', 'UserController');
            // CLIENTS
                Route::resource('clients', 'ClientController');
            // CATEGORIES
                Route::resource('tags', 'TagController');
            
            // CONTENTS 
                // IDE - GDE
                Route::get('/contents/ide', 'ContentController@ide');
                Route::post('/contents/ide', 'ContentController@ide_store');
                Route::get('/contents/gde', 'ContentController@gde');
                Route::post('/contents/gde', 'ContentController@gde_store');
                // Author
                Route::get('/contents/authors', 'AuthorController@index')->name('authors.index');
                Route::get('/contents/authors/create', 'AuthorController@create')->name('authors.create');
                Route::post('/contents/authors', 'AuthorController@store')->name('authors.store');
                Route::get('/contents/authors/{id}', 'AuthorController@show')->name('authors.show');
                Route::get('/contents/authors/{id}/edit', 'AuthorController@edit')->name('authors.edit');
                Route::put('/contents/authors/{id}', 'AuthorController@update')->name('authors.update');
                Route::patch('/contents/authors/{id}', 'AuthorController@update')->name('authors.update');
                Route::delete('/contents/authors/{id}', 'AuthorController@destroy')->name('authors.destroy');
                // Product
                Route::get('/contents/products', 'ProductController@index')->name('products.index');
                Route::get('/contents/products/create', 'ProductController@create')->name('products.create');
                Route::post('/contents/products', 'ProductController@store')->name('products.store');
                Route::get('/contents/products/{id}', 'ProductController@show')->name('products.show');
                Route::get('/contents/products/{id}/edit', 'ProductController@edit')->name('products.edit');
                Route::put('/contents/products/{id}', 'ProductController@update')->name('products.update');
                Route::patch('/contents/products/{id}', 'ProductController@update')->name('products.update');
                Route::delete('/contents/products/{id}', 'ProductController@destroy')->name('products.destroy');
                Route::resource('contents', 'ContentController');
            // CPAGES
                // Sections
                Route::get('/cpages/csections', 'CsectionController@index')->name('csections.index');
                Route::get('/cpages/csections/create', 'CsectionController@create')->name('csections.create');
                Route::post('/cpages/csections', 'CsectionController@store')->name('csections.store');
                Route::get('/cpages/csections/{id}', 'CsectionController@show')->name('csections.show');
                Route::get('/cpages/csections/{id}/edit', 'CsectionController@edit')->name('csections.edit');
                Route::put('/cpages/csections/{id}', 'CsectionController@update')->name('csections.update');
                Route::patch('/cpages/csections/{id}', 'CsectionController@update')->name('csections.update');
                Route::delete('/cpages/csections/{id}', 'CsectionController@destroy')->name('csections.destroy');
                Route::resource('cpages', 'CpageController');
            // BLOCKS              
                // blocks - advertisement
                Route::get('/blocks/create_advertisement', 'BlockController@create_advertisement');
                Route::post('/blocks/create_advertisement', 'BlockController@store_advertisement');
                Route::patch('/blocks/{id}/edit_advertisement', 'BlockController@update_advertisement');

                // blocks - videos
                Route::get('/blocks/create_video', 'BlockController@create_video');
                Route::post('/blocks/create_video', 'BlockController@store_video');
                Route::patch('/blocks/{id}/edit_video', 'BlockController@update_video');

                // blocks - text
                Route::get('/blocks/create_text', 'BlockController@create_text');
                Route::post('/blocks/create_text', 'BlockController@store_text');
                Route::patch('/blocks/{id}/edit_text', 'BlockController@update_text');

                // blocks - qrcode
                Route::get('/blocks/create_qrcode', 'BlockController@create_qrcode');
                Route::post('/blocks/create_qrcode', 'BlockController@store_qrcode');
                Route::patch('/blocks/{id}/edit_qrcode', 'BlockController@update_qrcode');

                // GLOBAL
                Route::get('/blocks', 'BlockController@index')->name('List of Blocks');
                Route::get('/blocks/{id}', 'BlockController@show');
                Route::get('/blocks/{id}/edit', 'BlockController@edit');
                Route::delete('/blocks/{id}', 'BlockController@destroy');

            // DOCTORS
                Route::post('/doctors/{id}/trash', 'DoctorController@trash');
                Route::resource('doctors', 'DoctorController')->except(['create','store']);               
            
        });
        // ROUTES for ADMIN
        Route::group(['prefix'=>'admin','middleware' => 'role:admin'], function () {
            // DASHBOARD
                Route::get('/home', 'HomeController@index')->name('home');
            // CLIENT
                Route::get('/clients/{id}', 'ClientController@admin_client_detail');
            // CATEGORIES
                Route::resource('tags', 'TagController');  
            // CONTENTS
                Route::resource('contents', 'ContentController');  
            // DOCTORS
                Route::post('/doctors/{id}/trash', 'DoctorController@trash');
                Route::resource('doctors', 'DoctorController')->except(['create','store']);
        });
        // ROUTES for DOCTOR
        Route::group(['prefix'=>'doctor', 'middleware' => 'role:doctor'], function () {
                // DASHBOARD
                Route::get('/home', 'HomeController@index')->name('home');
                // Update Profile

app/Lang.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Lang extends Model
{

    public function clients() {
        return $this->belongsToMany(Client::class,'clients_langs');
    }

    public function tags() {
        return $this->belongsToMany(Tag::class,'tags_langs');
    }

    public function csections() {
        return $this->belongsToMany(Csection::class,'csections_langs');
    }

    public function cpages() {
        return $this->belongsToMany(Cpage::class,'cpages_langs');
    }

    public function authors() {
        return $this->belongsToMany(Author::class,'authors_langs');
    }

    public function products() {
        return $this->belongsToMany(Product::class,'products_langs');
    }

    public function contents() {
        return $this->belongsToMany(Content::class,'contents_langs');
    }

    public function users() {
        return $this->belongsToMany(User::class,'users_langs');
    }

    //All Enabled Language with Sort Languages by English First
    public static function getEnabledLanguages() {
        $langs = Lang::where([['is_enable', '=', '1']])->orderByRaw('name ASC')->get()->toArray();
        $langsRes = [];
        foreach($langs as $key =>$val) {
            $langsRes[$val['id']] = $val;
        }
        $langData = []; 
        $langData[] = $langsRes['1']; // English Language on TOP
        unset($langsRes['1']);
        foreach($langsRes as $k =>$v) {
            $langData[] = $v;
        }

        return $langData;
    }
}
 

app/Http/Controllers/LangController.php
<?php

namespace App\Http\Controllers;

use App\Tag;
use App\Lang;
use Illuminate\Http\Request;

class LangController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $condition = [];
        $langs = Lang::where($condition)->orderByRaw('name ASC')->get()->toArray();
        foreach($langs as $key=>$val) {
            if($val['is_enable'] == '1'){
                $langsData['on'][] = $val;
            } else {
                $langsData['off'][] = $val;
            }
            
        }
        //echo "<pre>"; print_r($langsData); die;
        return view('langs.index')->with("langs",$langsData);
    }

   /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        // All Languages
        $cond = [];
        $cond[] = ['is_freeze', '=', '0']; // Skipping freez languages like english.
        $allLangs = Lang::where($cond)->get()->toArray();
        // get checked Languages
        $postLangs = [];
        $postLangs = $request->input('lang');
        foreach($allLangs as $key=>$val) {
            if(!empty($postLangs)){
                if(in_array($val['id'],$postLangs)) {
                    $is_enbl = '1' ;
                    $lang = Lang::find($val['id']);
                    $lang->is_enable = $is_enbl;
                    $lang->save();
                    unset($lang);
                } else {
                    if($val['is_enable'] == '1'){
                        $is_enbl = '0' ;
                        $lang1 = Lang::find($val['id']);
                        $lang1->is_enable = $is_enbl;
                        $lang1->save();
                        unset($lang1);
                    }
                }
            } else {
                if($val['is_enable'] == '1'){
                    $is_enbl = '0' ;
                    $lang1 = Lang::find($val['id']);
                    $lang1->is_enable = $is_enbl;
                    $lang1->save();
                    unset($lang1);
                }
            }
            
        }
        return redirect('/configs/langs')->with('success', 'Languages has been enabled successfully!');
    }

}

resources/views/langs/index.blade.php
@extends('layouts.dashboard')

@section('content')
<style type="text/css">
    #configure_langs_listing_form_group{ height: 400px; overflow-y: scroll; }
    #configure_langs_listing_form_group .form-item{display: flex;}
    #configure_langs_listing_form_group .form-item input {width: auto; height: auto; margin-right: 5px;}
    #configure_langs_listing_form_group .form-item label{font-weight: normal;}
    span#enabled_langs{background: #CBF6CC;display: block;padding: 5px;}
    span#disabled_langs{background: #F6D5CB;display: block;padding: 5px;}
</style>
<?php 
$base_url  = URL::to('/');
?>
<div class="page-heading"><h3>Language Configuration</h3></div>
@include('flash-message')
<div class="col-md-8 col-md-offset-2 langs-create-lang langs form large-9 medium-8 columns content">
	<section class="panel">
		<div class="panel-body">
            <form method="POST" action="{{ route('langs.store') }}">
            @csrf
                <div class="row">
                    <div class="col-lg-6 col-lg-offset-3">
                        <div id="form-field-langs" class="form-group form-checkbox-wrapper">
                            <label class="required">World's All Languages</label><br />
                            <div id="configure_langs_listing_form_group" class="form-control">
                                <span id="enabled_langs">Enabled Languages</span>
                                <?php foreach($langs['on'] as $k=>$v) { ?>
                                    <div class="form-item">
                                    <input 
                                    <?= ($v['is_enable'] == '1')?'checked':''?> 
                                    <?= ($v['is_freeze'] == '1')?'disabled':''?> 
                                    id="lang_<?= $v['id'] ?>" type="checkbox" class="form-control @error('lang') is-invalid @enderror" name="lang[]" value="<?= $v['id'] ?>" autocomplete="lang">
                                    <label for="lang_<?= $v['id'] ?>"><?= $v['name'] ?> ( <?= $v['code'] ?> )</label>
                                    </div>
                                <?php } ?>
                                <span id="disabled_langs">Disabled Languages</span>
                                <?php foreach($langs['off'] as $k=>$v) { ?>
                                    <div class="form-item">
                                    <input 
                                    <?= ($v['is_enable'] == '1')?'checked':''?> 
                                    <?= ($v['is_freeze'] == '1')?'disabled':''?> 
                                    id="lang_<?= $v['id'] ?>" type="checkbox" class="form-control @error('lang') is-invalid @enderror" name="lang[]" value="<?= $v['id'] ?>" autocomplete="lang">
                                    <label for="lang_<?= $v['id'] ?>"><?= $v['name'] ?> ( <?= $v['code'] ?> )</label>
                                    </div>
                                <?php } ?>
                            </div>
                            <span class="help-text">( Only enabled languages will display in client. )</span>
                            @error('lang')
                                <span class="invalid-feedback msg-error" role="alert"><i class="fa fa-exclamation-triangle"></i> {{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-lg-12 text-center">
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">{{ __('Save Languages') }}</button>
                        </div>
                    </div>
                </div>
            </form>
		</div>
	</section>
</div>
@endsection